swagger: '2.0'
info:
  description: 'Endpoint del backend de WheelsUS'
  title: 'WheelsUSZ Endpoint'
  version: '1.0.0'
host: 'echo-api.endpoints.wheelsus.cloud.goog'
x-google-endpoints:
  - name: 'echo-api.endpoints.wheelsus.cloud.goog'
    target: '34.122.92.141'
consumes:
  - 'application/json'
produces:
  - 'application/json'
schemes:
  - 'https'
  - 'http'
paths:
  '/create-user':
    post:
      description: 'crear usuario'
      operationId: 'insertCard'
      produces:
        - 'application/json'
      parameters:
        - description: 'Message to insertCard'
          in: 'body'
          name: 'message'
          required: true
          schema:
            $ref: ''
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Error'

