swagger: '2.0'
info:
  description: 'Endpoint del backend de Sigmath'
  title: 'Sigmath Endpoint'
  version: '1.0.0'
host: 'echo-api.endpoints.wheelsus.cloud.goog'
x-google-endpoints:
  - name: 'echo-api.endpoints.wheelsus.cloud.goog'
    target: '34.122.92.141'
consumes:
  - 'application/json'
produces:
  - 'application/json'
schemes:
  - 'https'
  - 'http'

